package com.dll.aoc;

import org.junit.Assert;
import org.junit.Test;

public class TrebuchetOneTest {
    @Test
    public void test() {
        String input = "twovgtprdzcjjzkq3ffsbcblnpq\n" +
                "two8sixbmrmqzrrb1seven\n" +
                "9964pfxmmr474\n" +
                "46one\n" +
                "7fvfourgkfkkbloneeightdrfscspgkdrmzzt1\n" +
                "15two6six\n" +
                "htxxfmfd7nb\n" +
                "sixfivesixeight4pfsgxvn9sfjfk5\n" +
                "pmjjpggvhkrq2\n" +
                "tvbrkhlxdsnine65\n" +
                "four5gkrptqninenbdvffour1z\n" +
                "foursgnlxmjtcrrfour7\n" +
                "3onetwogkhmllzvrsqzhhnkvdg\n" +
                "nineninegxknqzpsix28\n" +
                "1seven85189mv\n" +
                "gtwonejcncdlhpsxjrxnmpvfgtdrcdtd2nm\n" +
                "1ninemxzntjptl\n" +
                "qcmqfour2onesgplvgzkdltqtvzhtb1\n" +
                "seventhreerxqvgkzqhfxfdhnp628zxtbjklkpdtwo\n" +
                "fjdsgcsqppzdthreefour3one3lvmpm\n" +
                "sixsevenfivefourxf4mzhmkztwonepzt\n" +
                "nineninesixskjkbhx6nineoneightj\n" +
                "four6nzqxhhnrg\n" +
                "86fiveone9dhrkkh6\n" +
                "8ninetvnsrcsbpn\n" +
                "two43one\n" +
                "8vfvbrnclnmthree8onetwoeightthree\n" +
                "one2czxjgbzsn46ktj8twones\n" +
                "qfnlfivemqninextzppkfkb8\n" +
                "ntvcmxsevengxdtc3five\n" +
                "8lsfkbbxkscc\n" +
                "seven5817smvjfpdktwo6mdfngz\n" +
                "92hqxbchfpnine\n" +
                "tvxbltz53oneninethreeonek9\n" +
                "hvvjhd1\n" +
                "six1six7sevensixqcvhsfour7\n" +
                "seventwo2\n" +
                "2svpbhrlhfjhbkf3fourvvspkfmbvztmtpcxndfnine9\n" +
                "fivefour42\n" +
                "sixvstzdtfive3qzmbbx\n" +
                "rfcxmthzlgxgrmjncszdvlnp6\n" +
                "lhlncfjlhrqrfzr1\n" +
                "cqnkmtfj5\n" +
                "tctfngvrxljlt53pntbcfrftjpjvzqbqxh\n" +
                "6fgcdfive\n" +
                "4834sevenvssix1eight\n" +
                "rpxcthbpmhgrcxk4\n" +
                "threecthhnine781\n" +
                "pppqkscmthreeseven1sixfive\n" +
                "2tgrmvxpthree6\n" +
                "7ckxjmlpkqqqjtfiveeightbmmdoneighttnv\n" +
                "six2two\n" +
                "lsshzhtdfour24\n" +
                "mrjjgzsb92fivetwoxh3\n" +
                "5fourcqhk3two85fiveeight\n" +
                "lsxpkxfmq97one\n" +
                "b87twosshtxkkplq5zkrrqcmfn\n" +
                "threeqsnd64hthreeldbtfkqpbqpdlmtwo\n" +
                "eight2one\n" +
                "14r\n" +
                "71fourzrmsevenseven9\n" +
                "threesixmmcjzzml4\n" +
                "stnmbsix41\n" +
                "cztnnflpcl4txplfour\n" +
                "five6six4kxv\n" +
                "5oneqmmbnvgvbq6vsncbrjrsix7eightpzkhvrjz\n" +
                "kflckfgxfeightlr37fourfiveseven\n" +
                "9three7three\n" +
                "rkxbqnine7onevvqgzcvvjthreendkddfournine\n" +
                "fzzfstwo44vm\n" +
                "19648\n" +
                "7fivesixhdxhlgmv9\n" +
                "six9hzlctfiveonefour\n" +
                "66eightthree4nine\n" +
                "jcgk8three\n" +
                "tbctwonefive2eightsixbntmjceight\n" +
                "ninemrqkzsevengvq6\n" +
                "rsmmpmrlmq92fourfour453four\n" +
                "6eightbmjhnpbgnccfninefonenineglkfgp\n" +
                "8onefive7kn\n" +
                "eightrgzfdksevenftbvkt455oneightnl\n" +
                "3vxtwogxpdhjmqskjc\n" +
                "shzvnlgvvvthreenkv14eightbcmjd\n" +
                "2sevenlbq\n" +
                "1zfjpz1mdfourstvj7zpfxxlqf\n" +
                "twogm22trvplbsk29rbjtvctqr\n" +
                "twoqpgcbskdgh2tktbbpnzll7twoxljpdhthree\n" +
                "5nineeight6\n" +
                "936\n" +
                "218ptffour\n" +
                "1clztnnsix1\n" +
                "bsevengsxbpjmbg5eight\n" +
                "1cpeighteightpb\n" +
                "vrlnveight2twopxmtwo\n" +
                "fgrjr8six\n" +
                "5sevenspppgjtxbtqlzt\n" +
                "5sixczhncsix2qcqsevenfive4\n" +
                "kgcdpqclsggzm79nine\n" +
                "eighteightone6sevensixthree\n" +
                "92eight7plhftxkntl1two\n" +
                "5dqrhhqrrgmvrqznbgx4three3\n" +
                "twoone953cdkm5stzdbdh\n" +
                "heightwothreennzljtptwo94\n" +
                "6sevensevenfoursix5nine\n" +
                "cnbslkngtk9five58xpqvgjpqrnpjnzbk\n" +
                "onebrcg1bnfivekftnzpclqxvhchloneightzrn\n" +
                "four855dpknm\n" +
                "4hkdseventggkffhrkvsixcrsqjsix9\n" +
                "8seventwo\n" +
                "two9sixthree9cdrmqntmcv\n" +
                "525tg4h\n" +
                "five7kxrlmq1bzhdmhtgglmvzrtfbqqd3\n" +
                "bnbbsbhlcbktsqlpq69ninesfxhq\n" +
                "gndxnlmnrmnk29qkfxfoursnnbvjtq\n" +
                "5bzppjrgcpk\n" +
                "2three79pmgtcgmtdf2fjh\n" +
                "sixmmpbmtznseven62\n" +
                "4rrm\n" +
                "ztlthreesix28ninesix\n" +
                "j7fourfourfbrlxplk\n" +
                "zjhrqtqsix1\n" +
                "4three6hhndrlszfrgphcbonenxfive\n" +
                "jmg8hfsxfsvdxz3four7jfbczjmdhbpn\n" +
                "39ptfzqjfpnpxrnf7eight\n" +
                "three6jrcrgpfxg8vxgk8\n" +
                "57kvbczxn5eightfour\n" +
                "8xbdbrbpjp\n" +
                "sixtrhhl2tktvvmkffl5\n" +
                "three6fgsjtmnine54sm5k\n" +
                "ninenine3stfpft2nine\n" +
                "one61onenrhmtwos\n" +
                "pzdq8\n" +
                "pltd9sjdkrscxr25\n" +
                "dzsldkmzd1\n" +
                "vlvpfmz24sevenshcrvx389one\n" +
                "1rfvlnmfkdbmdjj\n" +
                "sixbzzbftqggn8zggtbcd\n" +
                "hzxzjhkvd5twofivedxfdlrdeighttwo\n" +
                "six9nlgcdznskrsb\n" +
                "sixrxkfhvsjxzbt4fivenineninenine\n" +
                "dsbmqpgmf8nine634two\n" +
                "fourknfzpthpf1\n" +
                "two9twovbmldd\n" +
                "5zgnnrxtwo2two2\n" +
                "fivezfvzfdxkmrbvtpdhqbmdhcthreedvlstmq28\n" +
                "ppfqqq75seven954\n" +
                "sgtjpsix3\n" +
                "twospnc9cnchkzthreegj\n" +
                "3eightwoqs\n" +
                "goneightghmkgksqfk2two2six\n" +
                "sixthree6bjzpqlsbgq2rkbffxtmprpddkxv\n" +
                "rkv43\n" +
                "bzfnbq8onefourthree4\n" +
                "3mqvr\n" +
                "fiveninefflpllcqzonejqqbtwofive43\n" +
                "tvoneightfour3three5\n" +
                "mvhlv6bzbjggrsvvxh4dfcpmrnhnq4\n" +
                "fcrsmfmpnmkfs3fivekblglhqmvfourchc7\n" +
                "svfmfbdrgd81one4\n" +
                "mf7threetwo8nine1\n" +
                "qngfr4gnnxbszqzsixp\n" +
                "px5gfx7two5seven9\n" +
                "4gp\n" +
                "8lxkgvpzxch6\n" +
                "3mdgqrvtgnthqnhpxteightfour\n" +
                "onethree899btbpjnxxjhone\n" +
                "fnjdzx5vrzc\n" +
                "four5twofour\n" +
                "9fivetwo2\n" +
                "threezlpsdhxvdlfpsvkxxnnine3\n" +
                "hvnnq9two2fourpdjv\n" +
                "bvjkdg9four1\n" +
                "2412\n" +
                "threethreeszmhdndctj1eight8lcqtwo3\n" +
                "cdnmjmxqrz6vrkkxtfour8cc\n" +
                "njldrqggdnfsix5\n" +
                "9csxcksh6three697\n" +
                "92four2sr32\n" +
                "3jdpqdjjct44oneone75pjgkgv\n" +
                "576sreighttwosixxzqmj7\n" +
                "twoscdxdlfddmfive54\n" +
                "ninefiveznine33\n" +
                "threenffnvx3\n" +
                "916tpsgsxmtml8\n" +
                "6five3\n" +
                "fdztvpctnr5dmbjnrjslr\n" +
                "16four\n" +
                "4oneightk\n" +
                "three5fouronenm\n" +
                "threezrksvlbdb891zfbbcdrbpd7\n" +
                "five821ndfftdbmbr3nine\n" +
                "ninehvdxftmgcvnkrlrvmmbb4nine\n" +
                "xkkzphgfv1two\n" +
                "3pm\n" +
                "ninetwobtjxdvnhv12\n" +
                "fiverbkmfbx8fiveeightksjzphkrj23rdlrtnb\n" +
                "kseightwo2fivesix\n" +
                "5snpchthree3\n" +
                "71oneone\n" +
                "6frxncksfxboneftdpvmnfdfxreighthrmnqc8\n" +
                "two48mhgdtlp246four3\n" +
                "993three8\n" +
                "threenine7twohbmcrpd\n" +
                "9bpdccqbts\n" +
                "kptwonejntgcdqdfffour4twobvtxnhqkl7\n" +
                "1637sevenfour\n" +
                "soneight6lbcrzdmhltpbkbjfivechxzfrqqgfeight\n" +
                "99five3hjvjrdmgl\n" +
                "qncqlreighthkfmbbfqx87five3\n" +
                "7jqkdsfour\n" +
                "ninemmvcxlkcrg1\n" +
                "mkdhgzcvmseven3onesnkhtxbgf7threestvjqn\n" +
                "nttgqsmsl4five1eighttwo9zg\n" +
                "one2ninefour5\n" +
                "bdfbveightseven1lcrshdgxznineeight\n" +
                "qsnvsonezqhsjmfive9one\n" +
                "6kvdrgkgznf1cmklmxgnine6\n" +
                "xkmzzdpknl661\n" +
                "ninefoursix7gnbmzd37\n" +
                "mmxmfnsrmt2bnhkmftxnjsix\n" +
                "fmhsrdtnrxlqgjttlgvmqxgzpl756sixllmdvblrvrrzkqgb\n" +
                "7xmppbvd976dqt87\n" +
                "fourzdctfglzzf1xdbfmrbfeightwor\n" +
                "8thncgqzvr989lthreeseven\n" +
                "5qmrzeight169\n" +
                "4qgvkmninegcsdgcthsp62onehczjhdxcgm\n" +
                "25tlppkmctwo2\n" +
                "668four4\n" +
                "rjbxtvfktchflstwo639one4\n" +
                "seven6eight4onehfztk\n" +
                "five53\n" +
                "nine33threethree3pznjbtxjmrrxm\n" +
                "19six\n" +
                "fivethreefivegxcqflqhjrn3fivehcn\n" +
                "vpbntqnpkjfninesix6341\n" +
                "7eightb7\n" +
                "bktffkqsx6fzvpnjhk\n" +
                "38jrjprtwo628\n" +
                "77tplflrp7\n" +
                "4one9one6\n" +
                "pkdhkbxrbshccxgknrjgseven44\n" +
                "49rthxdvlmeight\n" +
                "5twodhkpfn1\n" +
                "znine2fbsmeighttwo7\n" +
                "5ninexvmg\n" +
                "dbjbfmqtkp66\n" +
                "mdsrdjdnxkzr3xfm\n" +
                "two9twofive3\n" +
                "9kfivetg2five18\n" +
                "6fivenine2\n" +
                "2dlgpxsq7sixone6\n" +
                "tnqxgjbnc9bhqbgtwodxssml\n" +
                "18sixcjthreetdtprgsix\n" +
                "65sevenfive9nine4seven\n" +
                "nine34fiveqjdqc\n" +
                "threetzvxrb5vspdhrmjcnhtrzkqhd4\n" +
                "67nine8jrxt39\n" +
                "443oneklzsrtwo4tbbvxblk\n" +
                "xp7fourseven\n" +
                "ktsrninemlldztwo5ghqfgh55\n" +
                "five6eighteight7mtstgjlqmngzonetwonec\n" +
                "rmfourseventwothreedjtvf9\n" +
                "rlsgqhhvcdvthreekzjdssslmsixfour5rxk5\n" +
                "sgnfjqm4fivefiveone87nine\n" +
                "6twoonefive\n" +
                "sevenrftrnqrjs1\n" +
                "bcfgjklzfbnineninefivesrpcqtwo4\n" +
                "threek7seven1fxslmvnhmffqqvbfbhlceight\n" +
                "sixxzqz9fivethjgdv2\n" +
                "nineonefivesixtcrjd5\n" +
                "5645ptsjfrszgr8\n" +
                "1threezkpgczxr8four3oneqm\n" +
                "tvlfrfcnlc56eight8ninesix7seven\n" +
                "7clvmrdvdgjg\n" +
                "7mcstlktwo\n" +
                "dlxlpchr3eight\n" +
                "3ninelrzgkhx85\n" +
                "jlkqzonefourrvlptlxxgrthree4six\n" +
                "rxhpprsqtd982t\n" +
                "six4671nineonesix9\n" +
                "eightsixtm9vngskjglgvrbsqgcmxczbqqvxqxfj\n" +
                "vxfmc1six1ninesixnine\n" +
                "39fivesixthreevmpm4\n" +
                "xllclztxcxjskgfourlvggrvr25fourthree9\n" +
                "31sevensixninedpfrvvfftc\n" +
                "three64ctshdpcsfdjth95\n" +
                "fourgcqf8sixfivepsrdqvrld\n" +
                "5nine1qldrqhvfour\n" +
                "5three1three\n" +
                "6hjbgdqjtlppzoneninesevenqlmvgkq\n" +
                "eight1three6sixthree5two9\n" +
                "17141oner\n" +
                "five1two7\n" +
                "sxcfxblvfbtdtlkdpnineztnsfdkmeightvrr7fivejj\n" +
                "eight183krc8nkqk\n" +
                "sixthree38fourkgfbbv2sixsix\n" +
                "922threeeight4moneightsm\n" +
                "3threefive8bdzjs\n" +
                "onechvnhrfthreebqfive9\n" +
                "8sixgkvzgnfkjrrxrxvbvgvx\n" +
                "meightwo1dnbbpzrxftwo8\n" +
                "253lqt1bzfpqznz\n" +
                "klsgclc549rbksgrbbh56\n" +
                "3xksqcrhdsthree\n" +
                "55nxbjvps3nbmf\n" +
                "7qzzfourtwo1688\n" +
                "h5skqsrnnpxdone5fivefourkffrsblv\n" +
                "3fourfive2\n" +
                "25stdpqvgmzg9qksix5three\n" +
                "fivenxhkvbscrxx1j4\n" +
                "dtszrbcgpgxbh1\n" +
                "fivefvrp159three\n" +
                "68mdjsggnbtwokmthtwo286\n" +
                "xtwone7bkhjqkmmdkxvqtxfkpmckj5\n" +
                "btwonetjkkdfqphr2gkknfz7one\n" +
                "ninejgnxcchjqsevennvdjvttnqqsix6\n" +
                "395seveneight\n" +
                "lfrsoneoneeightfour6\n" +
                "four9prvhcqdnrgjl\n" +
                "qhbkninefive73six8\n" +
                "sixkqjtrs1hrmnt\n" +
                "5lmctnqtqc49eightnt\n" +
                "sixghthgcnpfeightseventwo3\n" +
                "vvvjbvnjfeight41nine\n" +
                "9gkxpcrql9three4\n" +
                "65seven4eightmjnh2gbjjstdgb\n" +
                "8four68seventhree\n" +
                "19924nine1lxnfzgt\n" +
                "fgjtbsfour4nine4vqfznznqxnsevenvzn\n" +
                "fiveone9bzshjmdvdsixxknhmmqskone8\n" +
                "xqjzgmdmnfivefourthreemmksmdsix6cct\n" +
                "eightklfnlkb9\n" +
                "rmtsdblmcghszsfgd66seven1bct\n" +
                "twoseven6\n" +
                "psbfmmmrppdfm5ninetwosixnine\n" +
                "rkcgdnslc9pjtqvgdmbvpkbbksxgr\n" +
                "mxjpns69\n" +
                "rspjpcv4fourthreesixfourninevlfive\n" +
                "2dgjgdn\n" +
                "66five8qxeight\n" +
                "five93\n" +
                "six7twovssixsixztrmfdrrvgqtdhmh7\n" +
                "32sqltqgoneightd\n" +
                "4five8tns1six\n" +
                "277\n" +
                "pmrzrckf6\n" +
                "8rglvpcttwo1twofive\n" +
                "fivethree644hrphp\n" +
                "fdpjb6\n" +
                "dfkpmgxfgfmtklbffk4sevenfive\n" +
                "nhqfpnvpsqpffour6neightfour\n" +
                "threeseven9eight67three8five\n" +
                "txttqnnineonefiveninesixlbscpqp1\n" +
                "three2sixtwotwo7smkmq5\n" +
                "8bjzjrnpspnine5\n" +
                "5three659fourfour\n" +
                "qrdrk7fouroneseven\n" +
                "three7threevhct\n" +
                "mpjpgfbt8five6fqjbghvbpcnine\n" +
                "7zonesevenzmlvfvzn\n" +
                "2hzldqdntffxhfpxlghf6threeninejrxngnjq\n" +
                "dfppvqcvthreessnnm65tqtn\n" +
                "56nine75rdkxdcmj\n" +
                "8twozvjkdltz4sevensixfive6\n" +
                "vzpzllmbghcccksevenjgjghqjr98\n" +
                "fgjsgxlh48sixg3three8\n" +
                "4eightfbppqltgxttoneoneseven3\n" +
                "six1eightddcthzd\n" +
                "fiveggljcppdeightnine5hsbfrtninenine\n" +
                "2xrdtzfnhpvpgone\n" +
                "982\n" +
                "two7nine7eightnine4\n" +
                "one431\n" +
                "eight9fmbfqxgzlskgjrrksr8six\n" +
                "9zhvdllsszd\n" +
                "4pnkpxrgltkdbztlnz2\n" +
                "4ninebkh6ninefiveh\n" +
                "five9ninevrzxhfnggfourfoursevensixlncsfdvrz\n" +
                "rqhjjxzeightnineseven7fnmbkrtqgr\n" +
                "8xfmqdone\n" +
                "pnszhd1trqb71gfhpjpq\n" +
                "9htfkgbxlht\n" +
                "sevenoneqgx29three5six\n" +
                "fourdlscbpbpb9four5jbdjzqqdthreerhqdsbb\n" +
                "five31sevennbmrbhtthreebzqxvthree\n" +
                "one4c\n" +
                "three38183threesix\n" +
                "6rtdclcbfbbdbeight1\n" +
                "2one8xdeight\n" +
                "2sixsixtwo\n" +
                "nine3pcjthmlmtljkrzxcdxkbmgzneightzcmtwohpdpkvqg\n" +
                "9two81qlhsrnfpdksdkd\n" +
                "threejrgxc4seven26njlmtbheightwodjh\n" +
                "lrjzhghhpk342threeninejskdnjjltt6\n" +
                "46threegj\n" +
                "ninedgpkqblftq2b3four\n" +
                "3951sixssgmjj3\n" +
                "8jteight4\n" +
                "three6mdvfkgrxcjmfoureightfour3\n" +
                "hvbf28\n" +
                "9fournine713six3\n" +
                "four1seven\n" +
                "763twoseventwonine4\n" +
                "ctpfmnsvcthree9sevencbqtjc3\n" +
                "sevensqdhvxd36\n" +
                "fourninergfmdxpdbt1ninefour\n" +
                "2kptonesixzpqrsqzhv\n" +
                "h4qcscfxfctjbqnff1sevengxvjjc3\n" +
                "d8cnjksdf\n" +
                "hzcgnine35fcbxtlg8rjhzbjfkv\n" +
                "jdvoneightdpfvzvp758fourfour\n" +
                "four27jhrgqnrjnkzffour5\n" +
                "fivetwoszrxz2fzfrbgqntjf\n" +
                "onergnqpl3\n" +
                "ccfqnc5twothreefoureight\n" +
                "grgsgxsevenkvzfjppnzq2sztcfive\n" +
                "9two94onesix\n" +
                "nine7seven7\n" +
                "eight36\n" +
                "plgsevenvfljnqvtfq5two\n" +
                "threethxdbnz49two2vdxbpqtpb\n" +
                "cf9fkrbrvjhssptthree\n" +
                "one5lrcn3klrcphllmz9\n" +
                "onesix6seven8tzgfdbm\n" +
                "964khvfxtrljs88\n" +
                "trszhb48fmseven\n" +
                "tdfxvnhrzv8threesevenkgp\n" +
                "ninegnmjxzbtcb32four9mlpkbfqdxdkoneightg\n" +
                "sixnineeightnhlqfslb2v\n" +
                "one83fc7zs\n" +
                "pxfkljdbdqqqvnrfivefoursg5nine\n" +
                "2onevh\n" +
                "1fgjrsdlgnbmsbzsevenfive\n" +
                "3nine87pmsqqntwojtnrksdtwo\n" +
                "two59kltcxhzszhdtwo\n" +
                "6451\n" +
                "sevenzscjhgpfgsseven7threeseven4threedlbtxtcvl\n" +
                "eighteight8sfsvhbkf9jgfrddx\n" +
                "qlvdplcqtrcj2eight4\n" +
                "sixbcpxtjt4onetwothree69\n" +
                "91fourrbblcl\n" +
                "twozvqbsx4\n" +
                "twogfh73\n" +
                "onesixljjrlonethree3rxtwofive\n" +
                "onefour62\n" +
                "b7vfplpqnine5\n" +
                "67dgbmmjsevenfivedktq\n" +
                "7foureighttwo4\n" +
                "sevenctctvfg51tsbzqgcvpvslqb\n" +
                "mjkeightwo7eightsb6one5xzsix8\n" +
                "151dht66\n" +
                "93tkbs\n" +
                "29two\n" +
                "foursixtwo5gprqslprxkrbfbmsl1six5\n" +
                "one3six3\n" +
                "three66rbh82bgtfzsfrkhrv\n" +
                "2sixfivethreefiveseven\n" +
                "fcjttg4onesixtwofive\n" +
                "15seven54\n" +
                "5kjdkr9htl\n" +
                "gclrsklbvkfbdcb9seventvdtdmmmksh52xkxtpmfpvk\n" +
                "spone7eight5xzjrlxrnzjtqgpdcgrsjn\n" +
                "vs3fourdkdlhx7rb\n" +
                "9ldxtdk3\n" +
                "4dppnthreetwodvkhjjrqh1zbqxntvtxgchv1\n" +
                "1sevenmsdrjgqfivevphqmxzghktwo6fdvkvqhj\n" +
                "tbptrcvxhs9qcdxcpvp\n" +
                "8five2ssrrhgtxfone\n" +
                "3clvbm2g961\n" +
                "four2onegkhbdfive5vxvxvtxglg6hxrtlhzjh\n" +
                "kfhcmflznrg9qnkkxqcsm2vqqtrdg8tjkshzpnddvd\n" +
                "eighttwojfktjcrqthreepssfour39\n" +
                "359nine2fivevvscbvggjhbnnzqtxfsbpb\n" +
                "vvshjlcfqt6qjvfjsix2tgsjbdxgppq1jmr\n" +
                "ninehhmeightcvqskvjptz2kdnhpptvkz54\n" +
                "39threefourndztxcl\n" +
                "sevenfive7\n" +
                "csmmpzfsix41\n" +
                "9cgqxtpdxt2\n" +
                "3mpzvlxrzvhtj\n" +
                "fourkqhzsjjjvx3six1\n" +
                "52one\n" +
                "nineltplrl8tfzqmnqeight\n" +
                "sixfourdqrfvrvbvfzzgb6\n" +
                "mqnxglzjk6qqhzksklvsmthreesixmvhmhbdkqpnxcsgvcsl\n" +
                "65\n" +
                "zqconeone85three\n" +
                "rxnhdflsqdqglxdmfxlxponeseven4one\n" +
                "88nkgcglftwodfxfhzxbqdpfrqmtwonenf\n" +
                "jzoneight9htkkpszpcqvkmlvl\n" +
                "388xnq\n" +
                "9xhlrqnkjpthreedfknpmqqtwo\n" +
                "4onemfzjfvmhhfive3two5pjdcf\n" +
                "djqjglztxs5nineeight8jdzone\n" +
                "four35ninefourfivethreecnhntp8\n" +
                "gxqxl6fourlfdtndgdql\n" +
                "fivenine6\n" +
                "1pqctbpbbgrmgqfqbzbjjt6\n" +
                "xzvjjfnfr28jblqseight\n" +
                "ctwone23\n" +
                "6sevenqjtwo\n" +
                "8nineplhlmsgjvs1\n" +
                "lmjgmltfivenine9\n" +
                "8gxnnnjonesixtwotwo1\n" +
                "2seven678cdxhkflhj3eightthree\n" +
                "djzninefour3one\n" +
                "vbqhjjhpzg86rkzdjzfj\n" +
                "eight1twotthreeqqlr\n" +
                "bkxseventhreezcjvdkxzksxrznp6four8\n" +
                "five77xcvphzcnlfbgbxnqbhfrldg\n" +
                "71qxqdncxdjsix\n" +
                "eight6one6jnpspgmhngzrfneightzdnrdhj\n" +
                "xb9skhpnfjsmq\n" +
                "jxgtk618fiveone1zr\n" +
                "8dkdnbfr\n" +
                "3llplnp4dzdxfhbvbn7two\n" +
                "eighttcgrbhrspktwo6eightddxhqqbprrf\n" +
                "eight2mpmzsevenrcbmsqg2cxjvmblnqbqdjsl\n" +
                "seventwo54\n" +
                "koneightsix22three\n" +
                "zdsnjr5vxrhkthkr8qmddrzclmrkprmvbll\n" +
                "fbkmfxncztwohjbfgkhgvcdkrpnc5\n" +
                "ksprkgxkjnineseven3fivebjpqhrmbdtwo\n" +
                "fourpss5\n" +
                "1three9fbnnrjcgllkvcs6\n" +
                "oneone9kjchnfsv9ffcdspfive54\n" +
                "26ninejctplmsgb\n" +
                "9ftfjrmvjblzqqmrdczpone3bphtmmkm\n" +
                "7lpssdtbc67mhnthree9cndbsthree\n" +
                "fourfour49four\n" +
                "nineeight8bzeight\n" +
                "128zpqftnxnqz2threettrhscsll\n" +
                "1xdtxcg4tkxtsnl\n" +
                "hmxbjczvgmcrd9mqsfivefourninethree\n" +
                "5hseveneighttwomgxmlmskr8\n" +
                "zdtbtszzkbk5\n" +
                "eight5nine6xthreefour\n" +
                "9rbfcnjztthree4v9vn\n" +
                "voneightqdtnrtc4\n" +
                "86cnzxs2three5\n" +
                "eight9seventhree\n" +
                "tjmrjgcfldqtbrvnzzxshxkrs3onefour\n" +
                "2rxplslzcglskjxgthk76cczdbxrp\n" +
                "sevenpdvsbhkknxqkqxfcz6bhmkxmhdbvhcvvhpmv49\n" +
                "three1twotwopr2lctfjb\n" +
                "zrbrqmh87dmxzmtfvthreelsleight\n" +
                "34dcnd8eightwombx\n" +
                "two9xnqtcfgq8tsqzvd3three\n" +
                "nine5fq3\n" +
                "eightsixfivemtcgzlbkheight4\n" +
                "qlspgfndmx5twobtjgzgvzmcone\n" +
                "5zlldrzrffgggtwo648\n" +
                "seventbqtkpfivel6\n" +
                "hjqbmfnnqzmf4\n" +
                "fiveqhdfsnjvqtwo6two\n" +
                "jftwone7\n" +
                "4twolqvglgxcc\n" +
                "twoqjmgjtrrjjt1eightcpj\n" +
                "eight9sevenmlkpsbzmtnhdrkbmj\n" +
                "trrpdninesix8oneqxtrzf\n" +
                "5sixtsxqdbnczhbvmfkvkc\n" +
                "tvbf2\n" +
                "sixtwonjssgpljqrxhlstfx4xbhqzlqktsixfour\n" +
                "kfxccb45tzsftztxjhgnxqsxknl29\n" +
                "tworjdcgsgvsix6\n" +
                "eightjbqfive26gfspjh3nine\n" +
                "2sqhleight7cfkhzrsevensevenfive\n" +
                "kzpzjcrl98sfive\n" +
                "sevenrsgtnine4pbgvrbcpf8\n" +
                "25q3qkcxlvhrxdonednbtcrrvjlnngq\n" +
                "twothree4lffpxvfcgqrkvdgzdsdjxjsh\n" +
                "seventhree34seventwofive9ckm\n" +
                "three25skfkvqdmbmsixxgqx\n" +
                "three1eightthreesix4\n" +
                "threeftjlv9\n" +
                "6spbhfckxcdrxlcg6hxcfive6five\n" +
                "8drbfjrgzvs834slzhsbgrjm2seventwo\n" +
                "sixsevenfmrvpqbgx4ncrmvfkjx62\n" +
                "lqfsslkmstwo7rgnqeightthreetnlnonehszkrghlnt\n" +
                "5onethreebxxfstvd\n" +
                "djchrbjcrddcqfourmnninesevenrdlpfxthr2one\n" +
                "three3threeoneninepcrjr1\n" +
                "twothreernxmhmtbn2fourtccrqhqs\n" +
                "lzzdpfourtwo1six\n" +
                "two3one3\n" +
                "zzcnprtjdr22286\n" +
                "seven5qjlfrhj7seven8\n" +
                "seven99\n" +
                "mtztq6one37oneeight\n" +
                "mrfcssmzxpvcz2sevenfourfivelpzqkvvdxmmpmxqshskfnh\n" +
                "nine8rtx71\n" +
                "1llzpvcdgmvoneonepksninefourthree\n" +
                "gbbvkcfive18two8twonineseven\n" +
                "2fivenztsix2nine\n" +
                "gjqnnr422seven4ppbsqdbpcfour\n" +
                "fourtwo5one7qfgpmmphdtl\n" +
                "pglzjrr4fivebclpf\n" +
                "slrrcqxxhtwoeightseven6\n" +
                "dnknxxkbjplrkjone2threesix9\n" +
                "htctqnkcmfqdxrzd9eight9seveneight\n" +
                "8sevenfiveninermlrrzpcdxkjkczhgpx6eightone\n" +
                "eighthnfxhrtssbmfxv6v\n" +
                "6fp539\n" +
                "sixzmsfqjzpvxjkhfqcrbss7xgg15\n" +
                "nine5ninevddknzczpxgzjx\n" +
                "jbcsf3\n" +
                "jjbstlskzxc5nine\n" +
                "jlrvgcbch7tnpfjnczdsrgddrseven156fvdmfhtl\n" +
                "one89\n" +
                "three52sevenlxxskf7gxh3gb\n" +
                "eighttwo59mqzdlqjdkkxgjhnktwoone\n" +
                "519six\n" +
                "1onemneightsixdlqx7\n" +
                "7fgszpqcj\n" +
                "sbfjtrfvnv6four\n" +
                "qtwonedvkninercj8\n" +
                "ntrnzldltrvtcsh8eight77sprgsvfdljthreecndckrzmjl\n" +
                "gtspn2\n" +
                "54six6mkjznlb\n" +
                "sevenonethree3sbpjqgltv\n" +
                "four8two\n" +
                "xdzrskv3974mgvjlhzbkddhcxzzxv\n" +
                "6three1mtlxshtxfpnine\n" +
                "14threeseven6\n" +
                "37threeonefpfgmz9\n" +
                "three3sevensixeightfive1nkjtndgrd\n" +
                "2dsmr7qhmnrgbsrvjmsbctwovb\n" +
                "gkdsnnqzlzdvcgthree3fivedzvpcfive6one\n" +
                "3vkftsclsxtxmsjeight\n" +
                "sglkcnzgz4mnhgblxqgdv69\n" +
                "tpcjb4one73s4\n" +
                "sevenrvhhxjcfqgs32six1pjvltwo\n" +
                "8zmktmxkbc5mpgrtnxmnp35fttpmdbhfm\n" +
                "1sevengeight\n" +
                "hghs1sixvvjpmlcponethree8kckgkf\n" +
                "gkbpflqvh1cbddlvdkzhfmzcfourkmckngsevenxkjknplzv\n" +
                "5sevenfk5qgfshtqseven155\n" +
                "dfjdtxjxb8fivefivebjtbggkdlpxlmnrcdt4jrrpnbtvlthrhmczn\n" +
                "2fivefivejxhh6\n" +
                "41threehtwo4nhzdn2\n" +
                "2fzngnxvvpjrqxk6\n" +
                "53sdthreeninexrfone\n" +
                "6qmrthlzgqeightrzrdglxvscgr\n" +
                "snkmhszcbmthree5threejsvkpkknpeighthbv\n" +
                "cmgb9seveneight\n" +
                "5djnine3bcffxgjbrhxbfhgthxb\n" +
                "1flqjgsf2ms\n" +
                "fivefive7onefour\n" +
                "threeeightksmhj94jvfvqrsgqrsevenj\n" +
                "jttgbfmh9468ddshrxnjthsix3\n" +
                "25four\n" +
                "9sixseventhreefiveninefive\n" +
                "eight5twoqrfgpkbdfc3qxfmchrjx8kpp\n" +
                "nineftnvllx1rjzkkt\n" +
                "gmeightwothree1fgfivejldgmt\n" +
                "nine966fivethreeninecpmgsxsxz\n" +
                "77bfhphxczdg2eight\n" +
                "89hcgjjtchsix\n" +
                "1onexps1\n" +
                "3fourkgm\n" +
                "hjgnbninevxdtpnct7bmstnczzteight23\n" +
                "twoone1qt8\n" +
                "43744\n" +
                "fourtfgn2\n" +
                "sixppztkbvllkltbs51xknnfive\n" +
                "tqxoneight5\n" +
                "twong3zdrbpqnb\n" +
                "fivebcrxk198three\n" +
                "435sfddjvfg56vkddkzhhj3\n" +
                "qcnhlbzmbld2fivebsix\n" +
                "zfsrtwothree8\n" +
                "nineeightfivetwomcjm2seven1\n" +
                "3gbnxlzxhvzzgfjjhf44fgbccpthhnkpht\n" +
                "3ccmrkbfour68ninetwonebz\n" +
                "sevenrccgdjrqj9one\n" +
                "fourzgdfbsnlb66txclxgp7\n" +
                "jmzlbtgbtl8three\n" +
                "6nine32pr\n" +
                "sixffcsmhlfiveklbmgj8nine\n" +
                "psmjrt65tppjqeightzqvglglnine1seven\n" +
                "fourninehhzh8seventwoone\n" +
                "48two2vzbrl\n" +
                "mdlzptrcsix3three9\n" +
                "sevenlgr3t\n" +
                "7sevenpphjhvdhkheightwojv\n" +
                "seven3756\n" +
                "four85\n" +
                "4twoonettmxjncsqmgsrxsf\n" +
                "fivesix6twofvzqxpphzmlkj\n" +
                "eight1twojrzspbfbzkftwo\n" +
                "5eightthree5\n" +
                "31ninecjnsevenjvbsvpphpxxkcnine9\n" +
                "nine5vnine486vrhbkgl\n" +
                "sevennineeight97qpdlfbskz7sfbtm\n" +
                "onernqbxt8twoone\n" +
                "gftjrbmkmngtshchbgfc1nvvt5\n" +
                "four5dgvsixzhlxnnmjhkhkljcfdpeight3\n" +
                "ttmfdxhd3ninekzbtsixnfmvfour\n" +
                "8pfkhxhmh8xkghgdk\n" +
                "nhs4threemxjpbgsix1s\n" +
                "ghtwoz1\n" +
                "sixdthree7vlfbpzcm1ndbbczvc\n" +
                "ninetwo183\n" +
                "twofxsdt36fcthreethreeseven\n" +
                "7grvvzqhcbeightwopx\n" +
                "twoninevknhnkgdmhmlbxkeighttwonine4\n" +
                "4fourdmclrghj2\n" +
                "sevenmtgvr8four76fivekdqbsmmtq\n" +
                "klgpeight5sbknbhvsixfive6\n" +
                "2vddxlzfpsrqsbsixlgrfnhone\n" +
                "jxfhlzcp6qctpqhb1\n" +
                "eightd1162jsfcsplrctwogcpzlhqf\n" +
                "one4four7xx5\n" +
                "threebqmzstphclb5fiveninethree\n" +
                "bkxfxxms6eightwoxz\n" +
                "nineeight4four\n" +
                "sdsgszdznng4sctkfiveszkdknqjf8\n" +
                "vtzmnllvvhrcfdlxcxxlqvzst1\n" +
                "htzxcxpvqj91sevenxrggdtjzbrgcv\n" +
                "ldcnbzstq4ktzdxgmcl\n" +
                "twohshbblseven4grzpdtfmjn13cmg\n" +
                "cktjnhdnine1three9mjqvnjtkseven\n" +
                "891ninesevenxbdjs\n" +
                "kxjpngdtwomxttdqcdkhdj686sixl\n" +
                "hsninefourcxfj3five3eight2\n" +
                "6eightgkkr1one\n" +
                "658one\n" +
                "zqgrxfourfour8\n" +
                "twobbnfkdtb9five21zcfiveoneightjgt\n" +
                "79jsm55twonine5\n" +
                "eightftk2two\n" +
                "eightbjbvqscs5pvmb14lgvgfv\n" +
                "four4four\n" +
                "qmzheight5hgfourkgtqfhjfournine3\n" +
                "twofzdqtvssx2\n" +
                "1fivefivesixsevenone47\n" +
                "xhrjffnine8\n" +
                "oneseveneight72fqgzscqt5\n" +
                "nine7fours58\n" +
                "three2fourseventhree\n" +
                "35ninesix\n" +
                "qgjsrxgqb5\n" +
                "fiveqghjjvjthree4eightqfgrhblkjtwo\n" +
                "9mvcm\n" +
                "96fourqzdsix\n" +
                "vbzqmmzbvrbxltvlfmcpfvnddmgsbb6four7onegn\n" +
                "three3qnlxmkhpctwosevenfourvmqmqlgfrsn\n" +
                "2seven5one2six15vgnqzpggn\n" +
                "sixljtvqzlh1\n" +
                "45onesix\n" +
                "foursix44eightseventhree\n" +
                "djsix84rnx8z34\n" +
                "1mkgthree8two9956\n" +
                "psgnl6six5seventwoone\n" +
                "546cfgr2three\n" +
                "thtpczmkskptzn9pqzncp\n" +
                "31threeninesn7xhqvrsv\n" +
                "threehmjpvctfhnmhs57ninepzfvq\n" +
                "teightwothreesixdzqhvljk84nineninesevenb\n" +
                "gvptkx9rlsnmtwoonesqfxmzkv\n" +
                "7twojszdrxcxfour\n" +
                "3eight617npsbbrpkjtzsmeight\n" +
                "3sixqntvpttddsixninemtpb4\n" +
                "1onefiveseven2fourseventwo6\n" +
                "67foursevensixsix2\n" +
                "one7qeightonehckxhxdfjjzsrdnj\n" +
                "38onehzjxg\n" +
                "4splxs1zfvfksevenkrzfive\n" +
                "fourfournkcj9\n" +
                "1ljmbhcpttjnine\n" +
                "2xnvfpdgccxfivellztmtpnc\n" +
                "ljvlxplhxfsjqv6sevennine44nine\n" +
                "qdonefourlnrzrgthbt1\n" +
                "twothreehvvhsxzqz1chvbcsxtll\n" +
                "82vmfjbvssmlgk2dbsljgvd3\n" +
                "xzfbfmbbxfeightgfz3lvzpzbpmv1four\n" +
                "oneeightfd5ninetwo\n" +
                "ghddk7six7xqmglkvnqonesix\n" +
                "six1eight\n" +
                "7five5ptkbvvvfive\n" +
                "3hftgthreehcfrsnl1fivetwo\n" +
                "7six12onebhpz\n" +
                "mkqjv8bzdnt9sevenfourtwo\n" +
                "five3mzgqnm\n" +
                "sixtwocbjxlgvp1twoseven\n" +
                "dkfmbzmvxseven971\n" +
                "bninetwojnsnkc7\n" +
                "ninekzcpfive4five3phz3\n" +
                "eight8143\n" +
                "eightrzdmxzb8eight6\n" +
                "5pdjm22ninej37two\n" +
                "fourtwo8fivetwosixthreetwo\n" +
                "ncttc71fourfivejpjzcgzpj4\n" +
                "5882three8glcvgnfhscbtmnqmnh\n" +
                "ngxkxtwo9pltbbmxrknvjheighttwo53\n" +
                "twoninenpqqqgsbsq3fjdk\n" +
                "eightsevensixhtsjvxjc8jxftgnptgqsixvcncglzlgq\n" +
                "sjxtcnt8gpeight7cbgffmgqksix\n" +
                "fdsn9threenineninetthree37\n" +
                "19rrfdqtpmonetqjdcjtxlhkptccjn6mtztqhvvtqftbv\n" +
                "vrhprdjsfour28p4\n" +
                "eightfiveeightninevdvnmbv58vrs\n" +
                "qdzhzrhlfl7hhxqzxqdxeight\n" +
                "svnbzgbhxjcx26xclfgs\n" +
                "5lcggbhzrmnknine83txffvcdonecrqvvjf\n" +
                "six5fpncsbbqbbcczcmbgrqmndxmrxloneone\n" +
                "1one6\n" +
                "88gctsmp7eightrvshklprtm\n" +
                "xf874onehhcknx\n" +
                "sevenvvncrhvxjxnzsftkfhsktwo3eightfour\n" +
                "8ngprdqfour\n" +
                "98fmrxpxzzbrjpxzqdxmv\n" +
                "2zbxzsthreefivefhdbhvjjxv6btwonef\n" +
                "jzkjcvpn924qjcbr97h3twoneff\n" +
                "foursix3\n" +
                "9pmtdjvrxjrponetjlxbdzbvrcjtc77\n" +
                "52twoeight2fourh8\n" +
                "kpzfztlzlkdprbmrhsjcxfzsbch31\n" +
                "4fivebtfjmfive6seven\n" +
                "ccttxjmheight6twothreelnjmfoureightnvcvpmpc\n" +
                "6twoz1dzv95\n" +
                "threelsmgdnxcsevenqr4xrtthzgkqxsrdssmjqv\n" +
                "fourgpvjxdg4qpvfivefive8nine\n" +
                "9mncmnhrclsq\n" +
                "9zjfmctz\n" +
                "pndgptggnsthree8xlcctvpsix6three\n" +
                "98npgrlkqmcninethree\n" +
                "fivexp6fourdpckhqpcxczrfbr\n" +
                "six2xdgsqdpsbmgftzvqhnjg\n" +
                "7ninepqheight2eight7g\n" +
                "2zrsevennlpcljnp\n" +
                "twoonethreevvpfp1jrhsevenfour\n" +
                "threebzmggv7bjm6cczkbsronetwo4\n" +
                "three1foursgvfdrrqmk4two6\n" +
                "onengzkkjsxsjlxxxthpd7xfcvkthreefour\n" +
                "sixnine5sixeighthlvmf\n" +
                "63gkmbsdc3fourmgrjhrlbqgcfxf\n" +
                "2bmldthree7skhhpxfonenineone\n" +
                "b6seven7\n" +
                "seven39\n" +
                "twoffxbsgpcxctmmvb4kdhn89\n" +
                "seven1fmgtseven\n" +
                "ninegxbdmztzzbqq6lgcvsbhzplqt\n" +
                "7twoonev\n" +
                "24nine\n" +
                "tvjmbzlsjtrtdhdlvnffmcfoursix6sevenonebvq\n" +
                "5jpntjsthree1threetkbsh7\n" +
                "sixone423fourqnczdxcpmsvjpzhl\n" +
                "33zdfourseven3\n" +
                "77lltwo5nineseven7djjmdqkqfd\n" +
                "4xfnpfbtdl7\n" +
                "two5ninejbrfrsbrsvzfivenineseventwo\n" +
                "89znjldjptdnfkeightkpcxdxcc3bkmfhtzkkh\n" +
                "qlkxd1rv44qlhhpjrninetwo\n" +
                "6l2rfscvcgdm7\n" +
                "rhtsrbrmlnfvseven1eight23dd\n" +
                "7xcglznxrjzsmhqnkqjhbjqxnjpjx15six\n" +
                "fourfiveq1vcsnnsxkmrcjscn4sevendbbtjh\n" +
                "6qcvjplvnine91rfjk51\n" +
                "jmdsgfxd5\n" +
                "tlzpvtsvkdsixtwo95\n" +
                "8threeeighthvhlqss\n" +
                "threetpxxlmfrhpf15\n" +
                "4twoeightsix\n" +
                "rg8nvrtzxjvfddkeightwofzs\n" +
                "tggqninemk1\n" +
                "mlchhftqkxtbhfpjsixnine817\n" +
                "231rpkxcvcz5fcztnqskqtwo\n" +
                "five9hhrtmp9twosixthreeeightv\n" +
                "9threeschsm17\n" +
                "hhreightfour171dtbmhzhhjb9fgbg\n" +
                "bhgp6\n" +
                "fourztzlhdr2hbdlv8fivenine\n" +
                "fourseven8seven\n" +
                "eighttwo8eight\n" +
                "two12\n" +
                "threenine76ndvklb\n" +
                "twoseven9jxfcthreecnrpvglksc\n" +
                "84fivehmf\n" +
                "jpgbtnrsb15eightgdtqmk\n" +
                "34two8eightbxqvc5nine\n" +
                "four4hsgjmtbfrvfivenine\n" +
                "threecfcx8ninefive3xone\n" +
                "cvhtlnlnhh71\n" +
                "four9sevenonenine9ninejlgmtvxmxseven\n" +
                "vttchshfgfpdbmpmp338\n" +
                "nfcdnhq6nineeight79\n" +
                "rgltnqzrzfqdjsfrhzmfivetwogklxqdhzbjtwo5three\n" +
                "five3n69fiveninesixtwo\n" +
                "nfhheight12clcqcnpdbz6nineseven7\n" +
                "eightgxtmstbthreedvrqllvp1ljqstbjdhcmbmbeight\n" +
                "two26four7three\n" +
                "6rtninethreefive\n" +
                "vhnqgdzzbxr9two7mdjzsx3lf\n" +
                "twothreepzxljpd6sixcmsxkcqkfive\n" +
                "6threesevensevenjzkcqthfivegmjvstrsix\n" +
                "five7fivetwofour\n" +
                "onesixseven767\n" +
                "36onehxdpmcqxsfbfive\n" +
                "2hdvqrlhs5six\n" +
                "pjfcjrnjnk9four99nineskshccmmnvxzvhvqmcprkdqvhhk\n" +
                "4gronexqnzdfthreejgqt\n" +
                "kvrsixtwofive2\n" +
                "eightfourone4hone\n" +
                "cgbjtdbvptworbcz3\n" +
                "jpgmhfour1\n" +
                "ngbgjhlstwokxc8onejlhczxvnjbrkqzdl\n" +
                "chbmqrz3fourthree\n" +
                "rgvmkpeightqdssbcgf9fivefive\n" +
                "5vgrscgshtbfgbljt5\n" +
                "pxgq5kffxbdjgq5cjnpzfdt738six\n" +
                "meightsvfb47xcdfkhf5\n" +
                "clzqdc4five1onexfxlxnltfourfour1\n" +
                "fivesix3threeseven\n" +
                "tworgklxh1threefourcsrsbj5\n" +
                "3fivepdppjlmmb6fkgrcbldbxsdjpbvbqgpj1nine\n" +
                "9clvlvsckdmjsbxzrmrhfour\n" +
                "fourlptwofqspctl913\n" +
                "28foursevenrfjfive5qrfsl\n" +
                "gfhmkfln2jcqttonethreetbmcdhhvbnmqdgsbrrmpk8\n" +
                "eight35qvkxtwo3fivevfive\n" +
                "26fivegpcqqsjr7five\n" +
                "three1seven4\n" +
                "9fiveonevmxhtndtfzmnxvtjkmr51six\n" +
                "64vgrgtwofour\n" +
                "four9one\n" +
                "nxjtdt2three1three96lfzglzcfour\n" +
                "355six\n" +
                "9lvqslrvdrd8six\n" +
                "9threetwo35six\n" +
                "two57\n" +
                "phpkcmfxvt7gphd1qglpmckhnj\n" +
                "sixthree1ffrdbsix4two\n" +
                "spbscvjfl8vvkpjkshkx3\n" +
                "5nnjdbjj3\n" +
                "bmmqrrkdcfbctmsk124eight9one\n" +
                "4rxdpvqlhn\n" +
                "seven13glpzfknqtxdqjq3qblzcjvx9\n" +
                "8bnkbzszkxkrrfdmcstvfvp\n" +
                "nndndjrs1qd1421\n" +
                "twovn9four8five\n" +
                "eightrc1\n" +
                "ltjvtcqfzdfourseven8kvcx43\n" +
                "vn6ninelr8\n" +
                "2seven1\n" +
                "7rldpqrfoureightthreesfhz11six\n" +
                "56fourkmvl6threegzfqnlrlz\n" +
                "8mkpcsnzmknmzpjppf8two7\n" +
                "bzgvzcpkqxmbxcqsix4qjzt28eightwoj\n" +
                "threesixxqkshhnine7njtvvxfmjl8\n" +
                "5seven6vqcd62sixone\n" +
                "three552\n" +
                "hsslkhbd88zjhqvgtzpfour1\n" +
                "oneone96fvjbmcnzrr\n" +
                "pspndcdtctwo6\n" +
                "v3one9\n" +
                "fivefournmrfrzghdh7twoxmpgkps772\n" +
                "vdkqxqnsthreefive25\n" +
                "kgjsevenczqrqf14pjchtfbnnninexhgn8\n" +
                "lqkhzjzm3six1one3\n" +
                "1three3l61seven\n" +
                "1flsfhznl\n" +
                "r8hnbpbtrzkstdg\n" +
                "hhrmnkktv7seven29fourpvjceight\n" +
                "2mbft\n" +
                "954five9fivegbmlz5\n" +
                "dshbfdqdjjgtxffjmllgvxjfrstgldgdxjsfxbone9tgseven\n" +
                "fourseveneighttdgghnfive7pchxddgggcq\n" +
                "8zx5seven7pffldzjhdb8\n" +
                "bpqslhkt33sixnlxckbbr2\n" +
                "xqmxvjcplh4seven\n" +
                "jd9zxmz2two1kvsghkvkpz\n" +
                "9blk3\n" +
                "6rjvmrjk46\n" +
                "onetwo6ninehdrlnxgbc\n" +
                "6drvnkssqzv5jfnineseveneight\n" +
                "sevenmvxlzmtwox49one1\n" +
                "8fxnnjr18fivefcf\n" +
                "five98sixkblsvns7mgttvhhz\n" +
                "85qkkg463lxdhzdtllqtv3\n" +
                "fivethree5eightfivessrnhsmdrnvssxfgxmsix\n" +
                "xgmqjone7j\n" +
                "pkclcg54\n" +
                "dvllcqqghh891pdlqnbtb6183\n" +
                "2qbnqkgncqrvlfntwo\n" +
                "seven7qdfzfpfivepnbhrqx48\n" +
                "682sixqtwotbgnsspzqcntlrhpzcq\n" +
                "2sffrxkgmsixfivetwokfvnlhz\n" +
                "sv9klzvnzsgjmoneseven\n" +
                "bzbppxbdpxs9\n" +
                "68ninetwo99four5grdrrkpr\n" +
                "mtfcscprzkeightfzdbhdndqh1njdfourtdtflbfjrth\n" +
                "8nvdtbrfrvfivesixtwodzxfhgpzlk6cgkbr\n" +
                "3slmzvnine5fm\n" +
                "eightone16nine\n" +
                "kdzrjbh2txzz5hbone96one\n" +
                "17pgtwofl41\n" +
                "eightoneqjvzv3\n" +
                "fivetwocrhmvxqkvbeightfive1qzcxvds\n" +
                "2htzsvdhvqvdjv";
        Assert.assertEquals(54605, new TrebuchetOne().Run(input));
    }
}