name: lint and test

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

on:
  push:
    branches-ignore:
      - "main"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Lint Code Base
      uses: super-linter/super-linter@v5.1.1
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_JSCPD_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        FILTER_REGEX_EXCLUDE: .*src/.*/.*Test.java
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Maven Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Test with Maven
      run: mvn --batch-mode clean test